#!/bin/bash

if [ $# -eq 0 ]; then
    >&2 echo "usage: logviewer [file_name]"
    exit 1
fi


if [ -r $1 ];
then
    echo "Viewing $1 on 127.0.0.1 port 5000 (http://127.0.0.1:5000) ..."
    python3 -c "

from flask import Flask, request


app = Flask(__name__)


@app.route('/update', methods=['POST'])
def update():
    last_id = request.json['last_id']
    with open('$1', 'r') as f:
        data = f.readlines()
    sending = []
    found = False
    for line in data:
        if found:
            if not (line == last_id):
                sending.append(line)
        if line == last_id:
            found = True
    if not found:
        if last_id == 'null':
            sending = data
    if sending:
        return {'data':sending}
    else:
        return {}

@app.route('/')
def log_page():
    return '''<!DOCTYPE HTML>
<html>
    <head>
    <style>
    html {
    scroll-behavior: smooth;
    }
    
    p {
        margin: 0;
        padding: 0;
        font-size: 10px;
        font-family: monospace;
    }
    
    #config {
        position: fixed;
        padding: 16px;
        top: 18px;
        right: 48px;
        width: 320px;
        max-height: 156px;
        background: rgba(180, 180, 220, .35);
        border: 1px solid rgba(0, 0, 150);
        border-radius: 16px;
    }
    
    #config div {
        padding: 8px;
    }
    
    #config h1 {
        margin: 0;
        font-size: 18px;
        font-family: Verdana;
        font-weight: 400;
    }
    
    #config label {
        display: inline-block;
        font-size: 14px;
        font-weight: 400;
    }
    
    #config input {
        display: inline-block;
        font-size: 14px;
    }
    
    </style>
    </head>
    <div id='config'>
        <h1>Logviewer (v1.0.0) <a href='https://github.com/jakedolan443/logviewer'>Source</a></h1>
        <div>
            <input id='autoscroll' name='autoscroll' type='checkbox'></input>
            <label for='autoscroll'>Autoscroll</label>
        </div>
    </div>
    <body id='log'>
    <script>
    var last_id = 'null'
    var autoscroll = true;
    
    function update() { 
            
        fetch('/update', {
        method: 'POST',
        headers: {
            'Accept': 'application/json, text/plain, */*',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({'last_id':last_id})
        }).then(res => res.json()).then(res => {
            let new_data = res.data;
            if (res.data) {
                last_id = res.data[res.data.length - 1]
                for (let i = 0; i < res.data.length; i++) { 
                    var span = document.createElement('p')
                    span.textContent = res.data[i];
                    document.getElementById('log').appendChild(span);
                }
            }
        }).then(res => {
            if (document.getElementById('autoscroll').checked) {
                const scrollingElement = (document.scrollingElement || document.body);
                scrollingElement.scrollTop = scrollingElement.scrollHeight;
            }
        })
    }
    update();
    setInterval(update, 2500);
    </script>
    </body>
</html>'''






app.run(host='0.0.0.0', port=5000)

    " > /dev/null
else
    echo "Could not read file. Check the file exists and you have sufficient permissions."
    echo ""
    echo "usage: logviewer [file_name]"
fi
